# A -> T, T -> A
# C -> G, G -> C
# GTCA -> (reverse)-> ACTG -> (complement) -> TGAC
# reverse and then complement

def complement_strand_of_dna(dna_string):
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    complement_string = ''
    reversed_dna_string  = dna_string[::-1]

    for molecule in reversed_dna_string:
        complement_string += complement[molecule]

    return complement_string

result = complement_strand_of_dna('AAAACCCGGT')
print(result)
print(result == 'ACCGGGTTTT')

result2 = complement_strand_of_dna('CCAAGTCGTCACTAAGGTCACAGAAACTATAGTAGCCGTCTTGTATTGTCCTAGACGAGACCGGCTGCCCTATTCCGCCCGCGCAACTTCGATGGGCGCCAATTGATAGCATGCAGACAATGAGCTTGACGTGAAGGACTTGGGACCCAGCTACGGTGACCCATTAGCTAGCTGTTTGCCGTTCGGTCGTACGTGTCACATGCCCCCTTCGCCCGCTCGGTCAGTAGAAGAGCAGAAGTAGGTAAATCAGTGGGGATGATATTGGTACCAGCAAGTTCCTTTTCTTTTGTGTCAAAATACGTCGCGGGTTGACGTACGCCCAGGTTCATGATCCCAAATCGCTACGCAGATGGGTGGCCCTTTAGCGACCCCCAAACTACAAGCTTCTATCAACGAACCGCCCAGGTGCGAAACCTGCAGCATTCTTCGGCACCATTTGAAGAAGGGCATGCAAAAAACCACCGCCACTCTCATTGACCTTGTGGCCATTGGCTATCAGCGCACTCAGTCTAATAGATTGGTACTTACGTCTATTAATGCAGGACGGTACGATCCGCGGCGGCGAATGGGAGTGTACATATTGTCTTTCCTGTTGGAGAGGATAGCTCACCGTATACGCCACCCTGTAATGATGATGTAGGCGGCCACCTTAGATCCCGTCGTTGCTCTACCGTTTTGAAGATTTACCACGCTGTATAGGGTAACCAAATGGAAAAAGCATGAAAGTACTGGGCGTCTGTAAGGATGCTTGTTGATAATGCTCATACACCAGTAAGTCGGATGCCGGTTAGAGTGGTGCGTATGACCGCATGGATT')
print(result2)